### ISSUE TITLE
Don't clobber Signal dtype

### ISSUE THREAD

**Issue by bburan** [LBHB/NEMS0#101]
Many stateful signals may be best represented as a boolean or integer dtype. However, somewhere in the processing pipeline they are getting cast to floating-point values. This is problematic because (at least in my code), I need them to remain integer or boolean. Hence, I have to recast them *back* to the appropriate dtype. This recasting process occurs on each evaluation of the modelspec, so this slows down fitting somewhat.

**Comment by svdavid** [comment]
I think this is taken care of now?
