### ISSUE TITLE
Data for tests?

### ISSUE THREAD

**Issue by christianbrodbeck** [LBHB/NEMS0#102]
What is the best way to get the files used by the tests? The tests seem to look for

- `/auto/data/nems_db/test/resp2.tgz`
- `/recordings/BRT026c-02-1.tgz`

**Comment by svdavid** [comment]
That looks like "unofficial" test data that's only reachable in the lab.
Sorry. I put them here:

https://s3-us-west-2.amazonaws.com/nemspublic/sample_data/BRT026c-02-1.tgz
https://s3-us-west-2.amazonaws.com/nemspublic/sample_data/resp2.tgz

I will add the BRT one to `nems.uri.get_demo_recordings()`  resp2 might be
deprecated.  What script(s) are you trying to run?

stephen

**Comment by christianbrodbeck** [comment]
Thanks! I'm trying to run all tests (and trying to add automatic testing through Travis).
