### ISSUE TITLE
Convert classmethods that operate on multiple instances of a class to standalone functions

### ISSUE THREAD

**Issue by bburan** [LBHB/NEMS0#19]
I'd like to propose making jackknife_inverse_merge a function importable from nems.signal. I think it looks very odd to have a classmethod that takes a list of class instances and returns a new class instance. Ivar tried to do that with a different function (merge_selections) before we agreed that it made more sense to have it be a stand-alone function (if you look at other Python packages, you'll see that functions that operate on lists of instances, such as pands.concat are stand-alone methods rather than classmethods). I know concatenate_time and concatenate_channels are classmethods, but I think they should be converted to stand-alone functions. I can fix these two if you agree that jackknife_inverse_merge should also be a stand-alone function.

The reason why I argue that this is weird is because it looks like we're doing something special with new_val[0], but we're not. We're just using it as shorthand to access a classmethod. If someone knows NEMS, they'll know what's going on. If it's someone new who's trying to learn NEMS, it's probably going to be confusing to them (and even if they figure it out, they may still not be completely sure they understand what's going on since it isn't the standard way most Python packages approaches these things).

**Comment by svdavid** [comment]
That makes sense. I'll switch this. I was trying to stick to a standard approach, but I guess there's a better standard.

**Comment by svdavid** [comment]
jackknife_inverse_merge moved out of recording object
