### ISSUE TITLE
Better signal slicing/dicing

### ISSUE THREAD

**Issue by bburan** [LBHB/NEMS0#2]
After my latest pull request, the methods for returning the raw data from the `Signal` now have an optional `chans` parameter. The arguments can be either `None` (meaning return all channels) or a list/tuple of strings indicating the channel names to return.

*After writing this proposal, I now believe that my idea to add a `chans` parameter is now a bad idea. The examples below offer a cleaner, more streamlined interface.*

When talking with @svdavid on Slack, he suggested there's still a use-case for potential index-based indexing. To support this, we can add a special method, `iloc`, (like in Pandas dataframes). The following will return a new Signal object where the data is the first 5 channels and first 20 timepoints:

    signal_subset = signal.iloc[:5, :20]
    
To get the raw data, one would do:

    x = signal.iloc[:5, :20].as_continuous()

To get epochs, one would do:

    epoch = signal.iloc[:5, :20].extract_epochs('trial')

Perhaps my original idea of adding a `chans` argument to the various methods was a bad one. Perhaps, it would be better to reimplement it slightly using a new method, `loc` (again, like in Pandas):

    # assume the channels are named '1kHz', '2kHz', etc.
    signal_subset = signal.loc['1kHz']

Above, `signal_subset` is a new signal containing only one channel. We can even extend this logic further to include time-slicing.

    signal_subset = signal.loc['1kHz', 1.5:3]
    signal_subset = signal.loc[('1kHz', '2kHz', '3kHz'), 1.5:3]

Above, `signal_subset` is a new signal containing only one channel and only from the span 1.5 to 3 sec. 

If we need to mix positional and label-based indexes (e.g., extract the first 5 channels and the time from 1.5 to 3 sec):

    signal_subset = signal.iloc[:5].loc[:, 1.5:3]

**Comment by jacobpennington** [comment]
I definitely like this - I think anything we can do to make using signals/recordings/etc feel similar to the scipy packages will help people feel more comfortable using our code.

One thing I would point out, however: it looks like you mixed time bin indexing with real time indexing. Maybe that was intentional - is the idea to have the method be smart enough to decide which one to use? I.e. one or more floats -> real time, all ints -> time bins.

**Comment by bburan** [comment]
Which example is mixing time-bin with real-time indexing? 

I don't think we should mix basic indexing with named channel/real time indexing. I think there's too much risk of confusion between ints and floats (Pandas tried to be too clever about indexing in the past, then realized it was a mistake and added `loc` and `iloc` to clearly differentiate between bin-based vs label-based indexing).

**Comment by jacobpennington** [comment]
Sorry, I didn't mean between examples - I guess what I meant was iloc was using one whereas loc is using the other, but keeping it strict like Pandas does makes sense. And i see the example at the bottom now with mixed, that looks good.

**Comment by bburan** [comment]
Ok. I'm working on this now. I have a need for it. Index-based is working. Now onto label-based.
