### ISSUE TITLE
Split standard_correlation into two functions (one for regular and one for jackknife case)

### ISSUE THREAD

**Issue by bburan** [LBHB/NEMS0#20]
I feel like these two cases are unique enough that the function would be easier to understand as different functions (e.g., standard_correlation_jackknife and standard_correlation.

**Comment by svdavid** [comment]
The other thing would be to break the validation prediction component out from this (into separate functions for jk and standard). This actually is more appealing to me, since I need to rework the jackknife code to save memory anyway.

**Comment by svdavid** [comment]
jackknifing is now built into the standard correlation. works even if the model was not fit using jackknifing.
