### ISSUE TITLE
Make a `lbhb_nems` repo for LBHB-specific processing

### ISSUE THREAD

**Issue by bburan** [LBHB/NEMS0#22]
A lot of code in `nems/preprocessing.py` is very LBHB specific, and relevant to only a subset of experiments. A `lbhb_nems` repo would be a great way to store the "history" of the lab's analyses. For example, you can have a `lbhb_nems.bburan.rdt.v1` containing my first set of preprocessing routines, followed by `lbhb_nems.bburan.rdt.v2` for my next stab. Finally, once we've published, we'd store those preprocessing routines in `lbhb_nems.bburan.rdt.nature.final`.

**Comment by svdavid** [comment]
Let's hold off on this for the time being. I agree that the preprocessing module is destined to be a mess, but there are so many moving parts already, I don't want to create another layer of complexity. Right now, there are so many layers between the single-line command to fit a model and the underlying process, that I really don't want to add anything else.

**Comment by svdavid** [comment]
Merged into #78
