### ISSUE TITLE
priors and bounds for modules

### ISSUE THREAD

**Issue by svdavid** [LBHB/NEMS0#26]
I noticed that some dexp models were getting stuck in local minima. I think this has to do with initial conditions. We might want to test/document reasonable priors for the different parameters. I'm also not super-happy with the current prior for the fir filter, though I don't have a much better idea.

And/or I want to develop preprocessing code that will set initial conditions based on inputs. Eg, for dexp, if you know what the dynamic range of the prediction going into the dexp and of the actual response, you can set some pretty good initial conditions that converge reliably.

Also, do we have a system in place for specifying bounds on phi values in a module?

**Comment by bburan** [comment]
The default priors are not well-chosen. I've already improved a few of them in my personal branch. 

As for setting initial conditions, I did have some preprocessing code that *generated* the priors in the old NEMS system. The priors were not meant to be set in stone without seeing what the data looks like (especially for dexp).

What do you mean by specifying bounds on phi? The priors define the bounds.

**Comment by svdavid** [comment]
I see. Hmm. It would be nice if there were a way to feed back improved priors into the master branch if possible. I know it's a hassle, but part of the goal of nems is to avoid having multiple people solve the same problem. Are you planning to merge your branch back in at some point? If things diverge too far, it might be difficult to do it later.

And about bounds, so would the way to set a hard bound would be to specify a uniform prior? and/or I see you've implemented half-normal. And is there a way to have fit_basic use these bounds? I assume you need to use your Bayesian fitter to take advantage of the full prior. Or maybe not?

**Comment by bburan** [comment]
No, it's just a matter of updating the modelspecs.

For bounds, you can certainly use a uniform prior. HalfNormal and Gamma constrain to the range of positive values. Beta constrains to the range 0 ... 1 (the Gaussian weight channel means should be Beta priors since they should fall in the range 0 ... 1, which is the main change I've made on my branch).

**Comment by bburan** [comment]
So, back to the idea of initializing priors while looking at the data. Ivar did leave a way to do that but didn't specify how it would be done. It would be done by writing our own initializer. Right now there's a simple keyword initializer, but we could write another initializer that takes the modelspec returned by the simple keyword initializer and then overwrite the priors with better ones based on the data.

**Comment by jacobpennington** [comment]
Related to updating the priors, there is also a utility function started on in modelspec.py that is meant to help with that using post-fit phi. Just takes a list of fitted modelspecs with the same modules and returns the mean/var/std for each phi. Still has issues with the phis that are ndarrays (like fir and wc) but it might be helpful.

**Comment by svdavid** [comment]
So sorry, I don't know if parsed Brad's "no" properly. Is it possible to draw information from the priors in scipy_minimize? I could simply implement a hard window in the cost function that forces predictions to some bad value if a parameter falls out of range.

**Comment by bburan** [comment]
Some scipy fitters support bounds. See `bounds` argument.
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html
