### ISSUE TITLE
Proposal: windowed buffer for signals

### ISSUE THREAD

**Issue by svdavid** [LBHB/NEMS0#27]
I'm not happy with the inefficiency of memory and disk usage by the current signal format, which requires spike data and stimulus spectrograms to be stored as rasters the length of the entire experiment. Also with having to duplicate recordings for jackknifing.  And finally, if we end up working with really large datasets, we'll **need** to be more creative about memory usage.

Ideas for changing the signal backend to save memory but also preserve performance: recording (and signal) method called "set_window" which defines the subset of signal times that should be used to generate the as_continous() output (and internal _matrix)
**responses** are stored as a list of spike times. set_window will generate a raster and store it in _matrix
**stimuli** are stored as dictionaries. set_window will tile the stimuli across the range of specified times and store it in _matrix.
**default signal** if not special case signal, just store the signal in _matrix, and have as_continuous select the subset of the signal specified by set_window.
DOes this seem reasonable? Would it make sense to start by making subclasses for these special case signals? There are still some details to work out for merging n-fold model predicitons back into a single recording object, but I think that's a solvable problem.

**Comment by bburan** [comment]
I agree with the subclassing of Signal to handle these special-cases. However, I'm not a fan of the `set_window` method. Why not return a new instance of the signal with the windowed data?

For example, for the default Signal, we already have a way to get a time-slice using the `signal.loc` method. For example, `signal.loc[:, 10:30].as_continuous()` will give you the dataset from 10 to 30 seconds. We can use this in lieu of the "set window" to create windowed signals. For example:

```
window_start = 10
window_end = 100
spikes = SpikeTimeSignal()
stimulus = StimulusSignal()

windowed_spikes = spikes.loc[:, window_start:window_end]
windowed_stimulus = stimulus.loc[:, window_start:window_end]

# The first call would generate the `_matrix` and cache it.
rasterized_spikes = windowed_spikes.as_continuous()
rasterized_stim = windowed_stimulus.as_continuous()
```

**Comment by svdavid** [comment]
I see, so calling the .loc method would generate a new signal with a rasterized matrix? That makes sense. So basically, we could store spikes/stimulus in their reduced native format and only require them to generate the rasterized signal each time we call loc. I like it! Esp because I think I can simply import some functionality in nems_db baphy into the signal object. 

And would it be complicated to develop a wrapper for .loc in the recording object? for fitting, it'd be important that the same window is applied to all signals.

**Comment by bburan** [comment]
The signal wouldn't get rasterized when we call `loc` (but it would get windowed). The return value of `loc` is basically a windowed view into the original signal. We can then generate the raster by calling `as_continuous` on the windowed signal. Or, if you like, we can add a third special indexer called `rloc` which will rasterize the signal when it's windowed. 

It wouldn't be hard to adapt `loc` to the recording object.

**Comment by svdavid** [comment]
Mmm. Might need to rethink a bit. The idea is that rasterization is slow, and we don't want the .transform method to require re-rasterizing each time it executes.  What if we use .as_continuous() to generate a new, rasterized signal and run the fitter on that?

So right, maybe rloc would solve the problem.

**Comment by bburan** [comment]
That's similar to what I originally had in mind. Sorry for not being clear.
So (thinking about the recording use-case):

```
rasterized_recording = recording.loc[signal_list,
time_start:time_stop].rasterize()
```

Note that signal_list can be `:` (meaning slice and rasterize all signals).

**Comment by bburan** [comment]
For the signal use-case, the first time `as_continuous` is called on an
unrasterized-signal, it's rasterized and the result cached in `_matrix` for
future use.

```
windowed_signal = signal.loc[:, time_start:time_stop]
windowed_signal.as_continuous()   # slow!!!!!
windowed_signal.as_continuous()   # now fast, because result above was
cached.
```

**Comment by svdavid** [comment]
OK, this seems quite doable. One thing I notice about the current signal object is that a lot of it is dependent on _matrix being a raster-style matrix. In this new form, would it make sense to store the data (spike times or dictionary of stimulus spectrograms) in a different data structure and then generate _matrix the first time it's needed?

Then I guess the only thing that would need to change is the save function. Any recommendation on how to save a dictionary to csv?

**Comment by bburan** [comment]
You mean the slicing is dependent on `_matrix` being a raster-style matrix?
Yes. The signal subclasses would have to provide methods that help the
slicer object do it's work (the reason we use slicer objects instead of
methods on the signal is for "syntatic sugar" (e.g., we can do
`signal.loc[:, lb:ub]` instead of having to do a more verbose
`signal.get_channels(channel_slice).get_time(lb, ub)`. But, what we can do
is require signals provide methods to handle the slicing of their internal
datastructure. The slicer object will then rely on these methods to
generate the new signal object. So, this means we need an API where we each
signal defines the following:

```
_get_time_subset(slice)
_get_time_index_subset(slice)
_get_signal_subset(slice)
_get_signal_index_subset(slice)
```

The slicer will then call the appropriate methods and return the new signal.

**Comment by svdavid** [comment]
Not just slicing but a lot of methods depend on _matrix.  Eg, .shape. It's fine, but I think we want to store the non-rasterized data in a different variable and then generate _matrix as needed. Maybe that can change in the long run (eg, if we want to buffer huge datasets on disk) but for now I think it'll work without a lot of specialized code for the subclasses.

**Comment by bburan** [comment]
So, one thing that occurred to me is that the unrasterized version of
SpikeTimes (or, more generically, EventTimes) would not have a sampling
rate associated with it as the times should be in seconds. So, we'd need to
provide that information when rasterizing.

Maybe we should come up with a proposed API that illustrates how each
subclass works and what methods they would support. For example, not all of
them have to support `shape`.

**Comment by svdavid** [comment]
Migrating the conversation back from Slack. Maybe we should keep it here so we can keep track of things? A couple things:

1. I implemented a concatenate time for the PointProcess signal (which I renamed from EventTimes).

2. Several functions that are currently specific to RasterizedSignal should probably be made generic and moved to SignalBase
-- load - This may call subclass-specific functions, but those details should be handled internally
-- list_signals - This currently assumes that all signals have JSON files. One more reason to keep metadata out of the hdf5 files. But alternatively we should make this function list signals of all types. Note that Recording is currently broken 
-- copy - is there any reason this can't simply be moved to BaseSignal from RasterizedSignal?
-- jackknife_* - if we write a generic RasterizeSubset function for each subclass, then jackknife* can be moved to SignalBase and simply call RasterizeSubset
-- epoch_to_signal - no change required?
-- add_epoch - no change required
-- shape -- I think this can generically be changed to `return [self.nchans self.ntimes]`

**Comment by bburan** [comment]
I agree with @svdavid. The current data input/output is a bit messy and should be refactored. I think we need to clean up the data loading/saving system a bit. I think moving all the code to `nems.data.io.hdf` and `nems.data.io.text` will clean things up a bit. Then, we can have functions such as `nems.data.io.hdf.load_raster`, `nems.data.io.hdf.load_point_process`, `nems.data.io.hdf.save_raster`, etc.

**Comment by bburan** [comment]
@svdavid - Totally agree with the `jacknife_*` methods. Ultimately, all the jackknife methods should be loose wrappers around a function that extracts temporal subsets and returns a `RasterizedSubset`. The jackknife methods can then offer different ways of extracting subsets (e.g., epoch-based, random times, etc.).

**Comment by bburan** [comment]
@jacobpennington: @svdavid and I talked a bit about the signal subclasses. Here's generally how we envision the process occuring:

1) The JSON metadata sidecar will contain information about the format of each signal (e.g., is it saved as a HDF5 file? is it a point process or a stimdict or a raster?). The load function will read in this sidecar and then use that to figure out which function (i.e., a format and signal-specific loader) to use for loading each signal. The load will then return a recording.

2) The class hierarchy will be as follows:
```
BaseSignal
- RasterizedSignal
-- RasterizedSignalSubset
- PointProcess
-- PointProcessSubset
- SparseRaster
-- SparseRasterSubset
```

When `.select_times(times)` is called on the "regular" signal subclasses, a `*Subset` class is returned. This class will default to pointing to a view of the data stored in the "regular" subclass, but contain information about the timepoints that were selected. When we finally call `to_raster` the `*Subset` class will then combine the data and timepoints to generate the raster needed for analysis. Note that subsetting the signal will *not* manipulate anything in the `epochs` dataframe. The `get_epoch_indices` functions need to be smart enough to take the epochs, check to see if an epoch falls within the selected timepoints for that signal and then return indices into a view of the subsetted signal.

3) For now, we will assume that all signals have been properly rasterized before passing to the evaluation/fitting functions. There's certainly use-cases where a fitter might want to use the event times (rather than a raster), so we should be open to this possibility.

4) The `*Subset` classes will raise an error if someone attempts to call `select_times`.

**Comment by bburan** [comment]
We have a decision to make. Do we want to keep the old methods that NaN out data (rather than keeping a subset)?

**Comment by svdavid** [comment]
Probably we can delete them, but can we keep them around for now? There are a lot of contingencies to consider.

**Comment by svdavid** [comment]
I just pushed an update to the nonraster_signals branch that stubs out some new non-method functions (is there a better name for these) in the signals library. 
load_signal() - load json file, figure out what sort of data file to load it
load_signal_from_stream() load json stream, figure out how to parse data_stream
list_signals() - modified from Ivar's code to list all *json files in the specified directory
concatenate channels() this is called by some plotting routines. I'm kind of inclined to get rid of this and replace it with a subclass-specific "append" function. that way the relevant code won't need to import anything but can just call methods in the signal

**Comment by svdavid** [comment]
@bburan Thanks for all your help. I had to force a tiny fix to get xforms.load_analysis to work. But we now have several things working:
- 3 different types of signal
- recordings and signals of all types can be saved and loaded to directories and tgz files. Haven't tested web URLs yet. 
- xforms-generated models now save and load properly -- again only tested with files.
- PointProcess and TiledSignals are generated by default for resp and stim signals in baphy.py. These are converted to RasterizedSignal at some point in the fit process. 

Still to do:
-- xxSubset signals. Or maybe they're working now?
-- Getting the hdf5 support working was surprisingly complicated, and I'm sure there's a way to do it better.
-- I'm sure there's a lot we can do to optimize performance of fitting with the non-rasterized signals, but I foresee those changes as tweaks rather than big overhauls

**Comment by svdavid** [comment]
Think this stuff is all done and working.
