### ISSUE TITLE
PSTH vs state plots

### ISSUE THREAD

**Issue by svdavid** [LBHB/NEMS0#35]
@jacobpennington I fixed up the PSTH for high vs. low state plots. I'm realizing that we need to work out some parameter specifications. There are a bunch of parameters for names of epochs, occurrences, signals to plot, etc., and it's quite confusing understanding what they all mean. And we may want to provide different parameter value to different plot functions, so it's not quite clear how they should be called from a high level. Eg, to get the PSTH state plot working with Daniela's data, I have to run `nplt.quickplot(ctx, epoch='REFERENCE')` because I want to average across all occurrences of all reference sounds. However, to plot a spectrogram, I really want occurrence one of the first epoch starting with "STIM_"... Though "REFERENCE will work in some cases for that. I will try to work through some specs for how these should be called.

**Comment by jacobpennington** [comment]
Okay, sounds good. Definitely needs more work, but hopefully it's an improvement at least!

**Comment by svdavid** [comment]
Yes, definitely looking good! You can see the nice plots now for batches 301 and 303. 

I think defining epoch as a regex match to "^STIM_" (Ivar has coded up this ability in signal objects) should work in most cases. For the time being, I hacked together something that works for both the passive and behavior data. That plus the default and occurrence parameters may actually be adequate for selecting the sample stimuli. Can we rename "default" to "rec_name" or "recording_to_display" and "occurrence" to "epoch_number_to_display"? or some more descriptive names?

At some point, it'd also be great to select different plots for some modules. For example, if controlling from a GUI, you might toggle between scatter and smoothed scatter rather than always showing both.

**Comment by svdavid** [comment]
This is basically working. May need to clean up eventually, but can close for now.
