### ISSUE TITLE
expanded fitting function

### ISSUE THREAD

**Issue by svdavid** [LBHB/NEMS0#41]
Follow up points after conversation with @jacobpennington this afternoon. Goal: expand fit options, find out what works:
- fitter keyword parser in xform_helper
- get fit_iteratively working with gradually tighter stop criteria and explicitly identified iteration groups
- NEW: pre-fit utility to freeze all phi except for a small subset of modules. eg, after pre-fit for the linear part (as is done now) fit ONLY the dexp output NL term. This can be an extra pre-fit step.
- get coordinate descent working
- head-to-head comparison of fit_basic, iterative+scipy standard, iterative+coordinate descent.
- LOW PRIORITY: mix and match iterative fitter where different subsets are fit with a different algorithm (eg scipy for NL modules and coordinate descent for linear filter?)

**Comment by jacobpennington** [comment]
@svdavid

> pre-fit utility to freeze all phi except for a small subset of modules. eg, after pre-fit for the linear part (as is done now) fit ONLY the dexp output NL term. This can be an extra pre-fit step.

- Just to clarify, do you want this available as a standalone option? The current fit_iteratively implementation can do this as part of its routine. If you want it specifically as a pre-fitting step prior to using other analyses, should be simple to just have a preprocessing wrapper call fit_iteratively with the appropriate indices for [[wc, fir], [dexp]] and tolerances [1e-4] (or whatever rough tolerance you've been using). 

> get coordinate descent working

- Works now as far as I can tell. I was using it when testing fit_iteratively. Does a little worse than scipy_minimize when dexp is included, but not by a lot.

**Comment by svdavid** [comment]
Working with @christianbrodbeck to improve coordinate descent. We identified a couple bugs and it's now qualitatively reproducing some of his previous results.

For the fit-subset-of-modules function, it would be nice to have it available in the initialization code, eg, if we want to fit the static NL after having prefit all the preceding modules.

**Comment by svdavid** [comment]
@jacobpennington Not sure if you've already finalized the fit_subset_of_modules code, but I just discovered something I started in `xforms.fit_basic_init_stp_freeze`. This really doesn't belong in xforms but rather should go in the initializers. Also it's specifically designed for STP rather than a generic user-provided list of modules. But maybe this has something useful in it.

**Comment by svdavid** [comment]
This is basically done. Still want to refine iterative fits and do some comparisons, but I think the core code is all in place and working.
