### ISSUE TITLE
pre-alpha is not a valid version

### ISSUE THREAD

**Issue by neheller** [LBHB/NEMS0#43]
Pip is complaining as follows:
```
UserWarning: The version specified ('pre-alpha') is an invalid version, 
this may not work as expected with newer versions of setuptools, pip, 
and PyPI. Please see PEP 440 for more details.
```
[PEP 440](https://www.python.org/dev/peps/pep-0440/) is suggesting semantic versioning. Perhaps something like 0.0.1a?

**Comment by bburan** [comment]
@neheller `0.0.1a` is fine. Can you please submit a PR? Be sure to add "closes #43" and it will automatically close this issue when accepted.
