### ISSUE TITLE
RasterizedSignal.as_continuous ignores segments option

### ISSUE THREAD

**Issue by bburan** [LBHB/NEMS0#52]
Should the `as_continuous` only return the subset specified by `segments`?

**Comment by svdavid** [comment]
Isn't cutting out the segments already taken care of by `RasterizedSignal.select_times` ?  ... Though I haven't tried it and I'm not sure what the intended function is. Should we spec out behavior more completely?

**Comment by bburan** [comment]
It is. Sorry. I totally forgot that I implemented it inside `select_times`.
Close #52.
