### ISSUE TITLE
Are abutting epochs overlapping?

### ISSUE THREAD

**Issue by lshaheen** [LBHB/NEMS0#56]
Should two epochs be considered overlapping if the end time of the first one is the same as the start time of the second?

I found that when extract_epoch is called in quickplot, half of the epochs are thrown away because each end time is the same as the start time of the previous. Not sure if this is what's meant to happen by default. If it is, maybe we can add fix_overlap as an option in extract_epoch so it can be turned off so that quickplot can access all the data?

For example:
an='/auto/data/nems_db/results/306/fre196b-08-1/env100.fir2x15_lvl1_dexp1.fit_basic.2018-04-09T23:55:02/'
xfspec, ctx = xforms.load_analysis(an)
extracted = ctx['val'][0]['resp'].extract_epoch('TRIAL')

len(extracted) is 40 when it should be 80

**Comment by bburan** [comment]
This shouldn't happen. It's a bug. Can you please update the unit tests to reflect this so that they fail appropriately (look in tests/test_signal.py)? I will take a look at the code.

**Comment by bburan** [comment]
#23 is related.

**Comment by bburan** [comment]
@lshaheen : I took a quick look at the code. I think I tracked down the problem. There are two issues:

1) We should allow `extract_epoch` to accept the parameters accepted by `get_epoch_indices` and then pass those parameters along. When implemented, this will help close #23. 

2) There's a bug in `nems.epoch.remove_overlap`. I'm pretty sure that line 18 should change `>=` to `>`. However, we need to confirm this is the case and add appropriate unit tests.

3) We need to update the `tests/test_epoch.py` and `tests/test_signal.py` to catch this kind of bug.

I'm not on my laptop right now (this computer isn't set up to run NEMS), so feel free to go ahead and make these changes and submit a PR. Be sure to add "closes #56" to the text of your pull request (also #23 if you update all the epoch manipulation functions, not just `extract_epoch`).

**Comment by lshaheen** [comment]
3: So test_signal.test_split_at_time actually already fails due to the bug. Not sure if that's enough?
2: I can change remove_overlap (which makes the test not fail). Seems like the right thing to do to me, but I have no sense of the broader picture and where else to look to confirm that won't break anything else.

**Comment by bburan** [comment]
Not sure why it's failing. Someone else may have broken the code. Go ahead with fixing step 2. As long as the unit tests pass, you should be fine. I can review the pull request to make sure you didn't break the bigger picture. Please make it a self-contained bugfix branch (no squashing dozens of unrelated changes into one branch). If you need the bugfix in your personal branch before it gets merged into master, you can merge in the bugfix branch.
