### ISSUE TITLE
bug in remove_overlap from epoch.py?

### ISSUE THREAD

**Issue by crheller** [LBHB/NEMS0#64]
If given an array of segments: [ [0 1.5], [1.5, 3] ] this function (remove_overlap) returns only [ [1 1.5] ]. Is this the desired performance? I would vote no. I'd think it would return [ [0 1.5], [1.5, 3] ] in this case. But I don't know where else this is used/what it was implemented for...

**Comment by crheller** [comment]
So, in this part of the code: `while (i < n) and (ub >= a[i, 0])` 

I think `(ub >= a[i, 0])` should be `(ub > a[i, 0])`

**Comment by lshaheen** [comment]
I think this is fixed, see pr #63

**Comment by crheller** [comment]
Ah... it appears I need to pull master haha thanks

**Comment by bburan** [comment]
Or rebase per Christian's suggestion?
