### ISSUE TITLE
standardize configs

### ISSUE THREAD

**Issue by svdavid** [LBHB/NEMS0#73]
Same config system for nems, nems_db, nems_baphy
Use this hierarchy(?):
1. read list of config variables and defaults from /config/defaults.py
2. overwrite any of those variables in /config/settings.py
3. overwrite any of THOSE variables in os.environ[]
Put instructions somewhere

**Comment by svdavid** [comment]
Looking good. Todos following Friday:

1. Graceful no-database failure for nems_db
2. "Plug-in" library support for nems (same general approach to config there)

**Comment by svdavid** [comment]
I'm going to migrate the plug-in discussion to a new thread.

**Comment by svdavid** [comment]
I believe new configuration system is in place, @jacobpennington ? or are we still working on changes in the main nems repo?

**Comment by jacobpennington** [comment]
The basic system is in place in the master branch but it does not reflect the changes made to incorporate the plugins updates.

**Comment by svdavid** [comment]
Ok different thread. Can close this Isse issue! Trying to clean up a bit.
