### ISSUE TITLE
Add documentation for FIR filter banks

### ISSUE THREAD

**Issue by bburan** [LBHB/NEMS0#82]
There is absolutely no in-line documentation (i.e., comments) or docstrings that explain how FIR filter banks work. Would be helpful to understand the shape of `x` and `coefficients` when `bank_count == 1` and when `bank_count > 1`.

**Comment by svdavid** [comment]
aha! added to the normalization branch. along with about a million other smaller changes... I don't think they mess with anything too critical, so I set up a pull request to master.

**Comment by bburan** [comment]
Thanks. The shapes make sense now!
________________________________

**Comment by svdavid** [comment]
Think we can close this?
