### ISSUE TITLE
The return value of this function is the same modelspec as passed into the function

### ISSUE THREAD

**Issue by bburan** [LBHB/NEMS0#84]
https://github.com/LBHB/NEMS/blob/b60dfa22d46cbb7d83d53839eb89dc6097b53bf9/scripts/demo_script.py#L106

If this is intended behavior, then don't return the modelspec (returning the modelspec suggests that a new modelspec was created rather than modifying the existing one in place).

**Comment by svdavid** [comment]
Ok, yet more evidence of a recovering Matlab junkie at work. The intention is not to modify in place. SO yes, we should always be making copies... Unless someone has a strong inclination to do it otherwise.
