### ISSUE TITLE
Need to document occurance parameter

### ISSUE THREAD

**Issue by bburan** [LBHB/NEMS0#85]
https://github.com/LBHB/NEMS/blob/b60dfa22d46cbb7d83d53839eb89dc6097b53bf9/nems/plots/quickplot.py#L64

For me, `None` signifies that you will do something special (such as average all occurrences) for plotting. However, it looks like you just set it to `0` in the code if it's `None`. If so, wouldn't it be better to set the default value to `0`?

**Comment by svdavid** [comment]
I agree, this is not well specified. The idea is that you might have a model fit with 100 different sounds, each labeled by the epoch "REFERENCE". setting occurrence=n should display the nth sound. In the long run this is meant to allow a GUI to browse through model predictions, one stimulus at a time. The current implementation is kludgy.

**Comment by svdavid** [comment]
Migration over to new modelspec system should take care of this.
