### ISSUE TITLE
more robust segmentation system, use for n-fold/last-step of preprocessing only?

### ISSUE THREAD

**Issue by svdavid** [LBHB/NEMS0#96]
Segmenting has a lot of uses, but there have been hiccups, particularly around the conversion back and forth between event times and event indices. Two major places where segmenting (ie, removing a subset of the data) currently happens in a normal xforms pipeline:
`preprocessing.remove_invalid_segments()`  --- currently uses segments to remove bad (miss, FA trials)
`recording.jackknife_by_epoch()` -- currently uses nans to remove validation segments.
It's unclear what would happen if we tried to segment a segmented signal, and I've avoided it. We've also run into hitches with segmenting used where it is. And jackknifing wastes a lot of memory by replicating the signals for each jackknife.
So I propose:
replace remove_invalid_segments with nan_invalid_segments.
then only use segments to remove nan and/or jackknife-related chunks of signals. This is basically the last stage of preprocessing before running a fit. 

Q: is there an efficient way to generate a segmented signal without creating a copy of the _data matrix? This would save a lot of memory in a 20-fold model fit. Currently it's not practical to fit this sort of model on the NAT + pupil data.

**Comment by svdavid** [comment]
Testing new system in normalization branch. Track "good" vs. "bad" samples in a new signal 'mask'. Seems to run much faster and requires a LOT less memory for jackknifing. But does require checking for the existing of 'mask' and acting appropriately in a number of places. (eg, for plotting, only find epochs that fall in a valid mask segment). Perhaps the mask can somehow be incorporated into find_epoch_indices, the same way as segments are currently? (problem of course is that find_epochs currently happens within a signal and the mask is in a different signal-- harks back to @bburan 's #58)

**Comment by bburan** [comment]
Did you look at masked arrays? Numpy has these built-in to the language and will usually do the right thing (some work will be needed for epoch handling though).

________________________________

**Comment by svdavid** [comment]
No, haven't looked at them. Interesting possibility. Though it looks like @crheller and I just effectively implemented them with a single mask for all signals. In theory also the signals themselves can persist as non-RasterizedSignals (saving space and cpu cycles). I'm tempted to wait and see how the current system works. 

Currently it deals with the key problems of getting mixed up on segmenting segmented signals and removing nans from est signals before fitting. And if it isn't going to magically fix the epoch handling problem, it may not be worth the extra time. 

As far as epoch handling, what if we implement find_epoch_xx in the recording object?  That way it can check for masking automatically.

**Comment by bburan** [comment]
I agree that the Recording object methods need to be smarter about extracting data from signals. However, I'd need more information about your proposal for `find_epoch_xx` before I can comment. For example, what is the `_xx` supposed to signify? Will I be able to specify that I want to keep an epoch if it's only partially masked? Will I be able to specify which signal contains the epoch of interest (e.g., using the synta `signal_name.epoch_name`)?

**Comment by bburan** [comment]
@svdavid Also, yes you can create a segmented signal without copying the data array. It just has to be implemented that way. The easiest way to handle this will be to define the segments as a type of special epoch (either saved in the epoch array or separately, you can call it `segment`). Then, you can use the various epoch manipulation methods (e.g. intersection, overlap) to pull out the data of interest. `as_continuous` can be updated to take a special epoch_name argument. To pull out only the segmented data for fitting, you would do `as_continuous(epoch_name='segment')`.

This proposal needs fleshing out before implementation though.

**Comment by svdavid** [comment]
@crheller You might want to review the current normalization pull request, which can close this issue.

**Comment by svdavid** [comment]
Esp, I'm not 100% sure everything still works with multi-channel recordings. esp PSTH calculation, thought there's not reason it shouldn't.

**Comment by crheller** [comment]
I think I fixed the psth stuff for multi-channel (mask needed to be multi-dimensional). I will double check that it's working asap

**Comment by svdavid** [comment]
I think we've got this working for the time being. I'm moving my code over to using "mask_for..." functions instead of "segment..." functions and then leaving segmentation to the fitter. Seems to save memory and speed things up in all cases.
